{
 "title": "P2 XDEI Dashboard",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Luminosity Map",
   "type": "geomap",
   "description": "La pregunta realizada a ChatGPT: \n\nIn a table with a column that specifies product type, and a column with time of arrival I want to select the latest arrived product by product type and its features. ",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lumens" } },
   "targets": [
    {
     "rawSql": "SELECT entity_id, time_index, longitude(location_centroid) as lon ,latitude(location_centroid) as lat, luminosity \r\nFROM ( \r\n  SELECT *, ROW_NUMBER() OVER(\r\n    PARTITION BY entity_id\r\n    ORDER BY time_index DESC\r\n   ) AS row_num\r\n  FROM \"mtopeniot\".\"etlamp\"\r\n) as latest_entities\r\nWHERE row_num = 1 limit 100;"
    }
   ]
  },
  {
   "title": "Last Motion Detection",
   "type": "canvas",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT entity_id, count as value \r\nFROM ( \r\n  SELECT *, ROW_NUMBER() OVER(\r\n    PARTITION BY entity_id\r\n    ORDER BY time_index DESC\r\n   ) AS row_num\r\n  FROM \"mtopeniot\".\"etmotion\"\r\n) as latest_entities\r\nWHERE row_num = 1 limit 100;"
    }
   ]
  },
  {
   "title": "Motion Detection",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "rawSql": "SELECT time_index AS \"time\", count AS \".\", entity_id AS \"value\" FROM etmotion ORDER BY time_index "
    }
   ]
  },
  {
   "title": "Door Status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT time_index AS \"time\", state AS \".\", entity_id AS \"value\" FROM etdoor ORDER BY time_index "
    }
   ]
  },
  {
   "title": "Luminosity Bar Gauges",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "lumens" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT entity_id, luminosity FROM etlamp ORDER BY entity_id "
    }
   ]
  },
  {
   "title": "Luminosity Gauges",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "lumens" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT entity_id AS \"type\", luminosity AS \"value\" FROM etlamp ORDER BY entity_id "
    }
   ]
  },
  {
   "title": "Luminosity",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "lumens" } },
   "targets": [
    {
     "rawSql": "SELECT time_index AS \"time\", luminosity, entity_id AS \"value\" FROM etlamp ORDER BY time_index "
    }
   ]
  }
 ]
}